Organization.create(name: 'ACYLA')
Organization.create(name: 'Andover')
Organization.create(name: 'Anoka')
Organization.create(name: 'Apple Valley')
Organization.create(name: 'Becker-Big Lake')
Organization.create(name: 'Blaine')
Organization.create(name: 'Blake School')
Organization.create(name: 'Bloomington')
Organization.create(name: 'Breck')
Organization.create(name: 'Buffalo')
Organization.create(name: 'Burnsville')
Organization.create(name: 'Centennial')
Organization.create(name: 'Champlin Park')
Organization.create(name: 'Chaska-Chanhassen')
Organization.create(name: 'Chisago')
Organization.create(name: 'Coon Rapids')
Organization.create(name: 'Cottage')
Organization.create(name: 'Delano')
Organization.create(name: 'Eagan')
Organization.create(name: 'Eastview')
Organization.create(name: 'Eden Prarie')
Organization.create(name: 'Edina')
Organization.create(name: 'Elk River')
Organization.create(name: 'Farmington')
Organization.create(name: 'Forest')
Organization.create(name: 'Hastings')
Organization.create(name: 'Hopkins')
Organization.create(name: 'Hudson')
Organization.create(name: 'Inver Grove Heights')
Organization.create(name: 'Lakeville')
Organization.create(name: 'Mahtomedi')
Organization.create(name: 'Maple Grove')
Organization.create(name: 'Mendota Heights')
Organization.create(name: 'Minneapolis')
Organization.create(name: 'Minnetonka')
Organization.create(name: 'Moundsview')
Organization.create(name: 'New Brighton')
Organization.create(name: 'Northfield')
Organization.create(name: 'North West Lacrosse Club')
Organization.create(name: 'Oakdale')
Organization.create(name: 'Orono')
Organization.create(name: 'Osseo')
Organization.create(name: 'Prairie Island')
Organization.create(name: 'Prior Lake')
Organization.create(name: 'RedWing')
Organization.create(name: 'Rochester')
Organization.create(name: 'Rogers')
Organization.create(name: 'Rosemount')
Organization.create(name: 'Roseville')
Organization.create(name: 'Saint Anthony Village')
Organization.create(name: 'Shakopee')
Organization.create(name: 'Spring Lake Park')
Organization.create(name: 'St. Cloud')
Organization.create(name: 'Stillwater')
Organization.create(name: 'St. Louis Park')
Organization.create(name: 'St. Michael-Albertville')
Organization.create(name: 'St. Paul')
Organization.create(name: 'Waconia')
Organization.create(name: 'Wayzata')
Organization.create(name: 'Westonka')
Organization.create(name: 'White Bear Lake')
Organization.create(name: 'Woodbury')